parameters:

    amp_subrequest_extra.kernel_response_listener.class: Amp\SubrequestExtraBundle\Listener\ResponseListener
    data_collector.subrequest.class: Amp\SubrequestExtraBundle\Collector\SubrequestCollector

services:

    amp_subrequest_extra.kernel_response_listener:
        class: %amp_subrequest_extra.kernel_response_listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.response }
        calls:
            - [ setContainer, [ @service_container ] ]

    data_collector.subrequest:
        class: %data_collector.subrequest.class%
        tags:
            - { name: data_collector, template: "AmpSubrequestExtraBundle:Collector:subrequest", id: "subrequests" }

